### ISSUE TITLE
HTTPError: 500 Server Error: Internal Server Error

### ISSUE THREAD

**Issue by DrexlerChao** [MGHComputationalPathology/slim#43] opened 2021-07-23 06:10 UTC
Dear Sir,
I follow the user guide https://dicomweb-client.readthedocs.io/en/latest/usage.html to retrieve instance.
My python version is 3.8.5 and python code as follow,
![code](https://user-images.githubusercontent.com/27002631/126740771-85407edb-d4e8-45fc-bbff-26efb6dc000d.png)

After the python code executed, the HTTPError as follow,
![Screenshot from 2021-07-23 12-54-21](https://user-images.githubusercontent.com/27002631/126740947-e800c001-d5c4-4bed-9d93-0346c62aa6e9.png)

Afterward, I try to use 3D Slicer DICOMweb Browser to retrieve the same instance, the HTTPError as follow,
![Screenshot from 2021-07-23 12-55-45](https://user-images.githubusercontent.com/27002631/126741253-a0decedc-c8f2-47a8-bb8d-a2955d077566.png)

The error is very interesting, because I can search the instance UID, but I can not retrieve it.
Did I miss something that cause the error？

**Comment by hackermd** [comment] 2021-07-23 19:44
@DrexlerChao  it is hard to say what causes the error, but it doesn't appear to be an issue with the server (or the data) rather than the client. Did you inspect the server logs?

**Comment by DrexlerChao** [comment] 2021-07-27 02:43
@hackermd Dear Sir,
I use the cmd to check DCM4CHE server logs
$ docker exec slim_arc_1 cat /opt/wildfly/standalone/log/server.log
![log](https://user-images.githubusercontent.com/27002631/127083677-84aafeb8-bac5-42ea-86e8-9970f0661041.png)
The log said java.nio.file.NoSuchFileException: /opt/wildfly/standalone/data/fs1/2021/07/19/EE6E26AB/73022895/DD31F674

I try to find the file DD31F674 in the Docker container as follow,
![container](https://user-images.githubusercontent.com/27002631/127083303-60fd9461-0fa8-4f42-a5c9-74ae43fc3dbb.png)
Only date 23 exist, w/o date 19.

Afterward, I keep looking for the file DD31F674 in the Docker volume as follow(RED rectangle),
![volume](https://user-images.githubusercontent.com/27002631/127083894-f17b82c8-ed49-4fbd-9667-761d0ccd1f99.png)

Yes, the file DD31F674 in the this volume,
![filesystem](https://user-images.githubusercontent.com/27002631/127084154-fafd9a7f-8697-4b5c-934b-dfb47f2182fc.png)

And the volume include date 02, 09,13, 14, 19, but w/o date 23.
![Screenshot from 2021-07-27 10-17-48](https://user-images.githubusercontent.com/27002631/127084967-ed6b3773-0d10-486d-9bd9-2dd672a83176.png)

The 500 Server Error seems like the file path error and docker container/volume storage inconsistent.
Here is docker log file for your reference,
[docker_log.txt](https://github.com/MGHComputationalPathology/slim/files/6882285/docker_log.txt)

If you have any further suggestion or idea, please feel free to let me know.
Sincerely appreciate. Thanks.

**Comment by hackermd** [comment] 2021-07-28 19:19
> If you have any further suggestion or idea, please feel free to let me know.

Not sure. This could be an issue with the containerized DCM4CHE archive getting somehow out of sync with the database/filesystem storage volume.

I am closing the issue, since it appears to be unrelated to Slim. I would recommend reporting the issue at https://github.com/dcm4che/dcm4chee-arc-light

**Comment by hackermd** [comment] 2021-08-09 15:46
@DrexlerChao I was able to reproduce the error and reported the issue to the DCM4CHE maintainers. Based on their feedback, I updated the docker compose configuration and can no longer reproduce the error. Could you kindly test on your end, too?

**Comment by hackermd** [comment] 2021-08-10 21:15
Closing this issue since I no longer encounter the error after the update of the Docker compose configuration.

**Closed by hackermd** 2021-08-10 21:15 UTC
Labels: bug

**Comment by DrexlerChao** [comment] 2021-08-16 06:00
@hackermd Hi Sir,
Sorry for the delayed response!

After install the latest version of Slim, this issue is fixed.
Thanks for your great support.
